name: flutter_project_template
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  card_loading: ^0.3.2
  http: ^1.2.0
  dio: ^5.4.0
  intl: ^0.19.0
  sqflite: ^2.3.2
  path: ^1.8.3
  top_snackbar_flutter: ^3.1.0
  material_dialogs: ^1.1.4
  lottie: ^2.7.0
  intro_screen_onboarding_flutter: ^1.0.0
  web_socket_channel: ^2.4.0
  open_route_service: ^1.2.4
  location: ^5.0.0-dev.8
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  image_picker: ^1.0.7
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  firebase_messaging: ^14.8.0
  firebase_storage: ^11.7.0
  firebase_database: ^10.5.0
  firebase_analytics: ^10.10.0
  json_theme: ^6.4.1+2
  wtf_sliding_sheet: ^1.1.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/yellowdustbin.png
    - assets/icons/
    - assets/garbage_darktheme.json
    - assets/garbage_lighttheme.json
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
